# Generated by Django 5.0.6 on 2026-01-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_add_project_id_statuses_list_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page_name',
            field=models.CharField(choices=[('home', 'Главная'), ('tasks', 'Задачи'), ('projects', 'Проекты'), ('settings', 'Настройки'), ('users_list', 'Список пользователей'), ('departments_list', 'Список отделов'), ('project_id', 'Строительные участки'), ('statuses_list', 'Статусы')], max_length=50, verbose_name='Страница'),
        ),
    ]
