# Generated by Django 5.0.6 on 2026-01-01 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to=settings.AUTH_USER_MODEL, verbose_name='Начальник участка')),
            ],
            options={
                'verbose_name': 'Строительный участок',
                'verbose_name_plural': 'Строительные участки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('cipher', models.CharField(max_length=50, verbose_name='Шифр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('construction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.constructionsite', verbose_name='Строительный участок')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'unique_together': {('code', 'cipher')},
            },
        ),
        migrations.CreateModel(
            name='ProjectSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_sheets/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('executors', models.ManyToManyField(blank=True, related_name='project_sheets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Проектный лист',
                'verbose_name_plural': 'Проектные листы',
            },
        ),
        migrations.CreateModel(
            name='ProjectSheetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('note', models.TextField(verbose_name='Заметка')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_sheet_notes/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_sheet_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.projectsheet', verbose_name='Проектный лист')),
            ],
            options={
                'verbose_name': 'Заметка проектного листа',
                'verbose_name_plural': 'Заметки проектных листов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет')),
                ('status_type', models.CharField(choices=[('sheet', 'Проектный лист'), ('stage', 'Этап проекта')], max_length=10, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'unique_together': {('name', 'status_type')},
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата-время')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_stages/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='Проект')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'status_type': 'stage'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stages', to='projects.status', verbose_name='Статус этапа')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проекта',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='projectsheet',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'status_type': 'sheet'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_sheets', to='projects.status', verbose_name='Статус'),
        ),
    ]
