# Generated by Django 5.0.6 on 2026-01-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_responsible_department_to_project_sheet'),
        ('user_auth', '0002_pagepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsheet',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_sheets', to='user_auth.department', verbose_name='Ответственный отдел'),
        ),
    ]
